### ISSUE TITLE
phashion_ext.c:6:25: fatal error: ruby/intern.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by ASLANTORRET** [westonplatter/phashion#46]
I've got error "phashion_ext.c:6:25: fatal error: ruby/intern.h: No such file or directory compilation terminated. make: **\* [phashion_ext.o] Error 1
"          when installing phashion.

How to solve this problem ?

**Comment by westonplatter** [comment]
@ASLANTORRET ok, thanks for the update. I'll close this issue.
