### ISSUE TITLE
checking for sqlite3ext.h... *** extconf.rb failed ***

### ISSUE THREAD

**Issue by ghost** [westonplatter/phashion#53]
on OSX 10.8.4

checking for sqlite3ext.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/xxx/.rvm/rubies/ruby-2.1.3/bin/ruby
/Users/xxx/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.

**Comment by danielricecodes** [comment]
Apparently installing RMagick - or one of its dependencies fixed this.  I'm on Ubuntu 22.10 using Ruby 2.7.7.  

`sudo apt-get install libmagickwand-dev` is all it took.  The gem installed just fine after this.
