### ISSUE TITLE
Publish 1.2 on RubyGems?

### ISSUE THREAD

**Issue by duffyjp** [westonplatter/phashion#58]
RubyGems only lists up to 1.1.1
https://rubygems.org/gems/phashion/versions

Is 1.2 ready for prime time?

**Comment by globalcitizen** [comment]
:+1: I'm also after storable values from the hash functions.

**Comment by westonplatter** [comment]
@duffyjp published, https://rubygems.org/gems/phashion/versions/1.2.0.

**Comment by westonplatter** [comment]
@duffyjp I'm closing this
