### ISSUE TITLE
Generate and upload new gem version to Rubygems repository

### ISSUE THREAD

**Issue by basestylo** [westonplatter/phashion#62]
The last available version is 1.2.0 but master branch contains a [changelog](https://github.com/westonplatter/phashion/blob/master/CHANGES.md) that shows 1.2.1 as latest version. 

In addition, [version.rb](https://github.com/westonplatter/phashion/blob/master/lib/phashion/version.rb) also contains 1.2.0 as current version.

Thanks!

**Comment by westonplatter** [comment]
@basestylo my bad. You're correct 1.2.0 is the most up to date version (via the version.rb and Rubygems release). I stubbed out 1.2.1 version on the changelog in preparation for future changes. I've corrected the changelog via https://github.com/westonplatter/phashion/commit/3c0e310b31637a1c156ffcb7c95e30cd6c12b7e7.

**Comment by basestylo** [comment]
Wow, perfect 👌 . Thanks for your effort.

**Comment by westonplatter** [comment]
@basestylo You're welcome. Glad that fixed it. :) I'll close this issue now. Feel free to reopen if I missed something.
