### ISSUE TITLE
Tests fail on Ubuntu 16.04 and above

### ISSUE THREAD

**Issue by MatzFan** [westonplatter/phashion#78]
I installed from `master`, complied and ran the tests on my local system (Ubuntu Bionic 18.04). The following is the relevant part of the result:

```
  1) Failure:
TestPhashion#test_mh_distance_from [/home/me/dev/phashion/test/test_phashion.rb:90]:
Expected |0.1 - 0.06770833333333333| (0.03229166666666668) to be <= 0.028.

  2) Failure:
TestPhashion#test_mh_hash_for [/home/me/dev/phashion/test/test_phashion.rb:83]:
Expected |0.1 - 0.06770833333333333| (0.03229166666666668) to be <= 0.028.

21 runs, 69 assertions, 2 failures, 0 errors, 0 skips
```

My [fork](https://github.com/westonplatter/phashion/compare/master...MatzFan:travis_xenial) using Travis-CI Xenial (16.04) produces the same result, as you can see [here](https://travis-ci.org/MatzFan/phashion/builds/531367879). I have not checked whether whatever causes this affects the fingerprint calculation  as well as mh_hash. 

Library versions (my local machine):
libpng-dev 1.6.34
libjpeg-dev 8c

**Comment by westonplatter** [comment]
@MatzFan thanks for seeing this and making the adjustments. This looks like the right move, especially since there have been no changes to the ruby or underlying C library. Merging :)

**Comment by westonplatter** [comment]
@MatzFan thanks for demonstrating the resolve code changes. I copied your same approach in #88.

Would you have any interest in helping maintain phashion and release new versions? I don't spend much time in the ruby world anymore so digging in the details here is harder for me. If you're interested, let's talk.

**Comment by MatzFan** [comment]
@westonplatter happy to give it a go, so long as I don't need to go near the C library! Not used phashion since my attempt to crack Google's reCAPTCHA a few years ago. I still have millions of pHashes of street signs somewhere..

**Comment by westonplatter** [comment]
@MatzFan added you as a repo collaborator.

**Comment by westonplatter** [comment]
Given the CI is running successfully on ubunut-22.04, I think I can close this out. @MatzFan does closing this issue make sense to you?

**Comment by MatzFan** [comment]
@westonplatter agreed.
